import * as THREE from './three.module.js';
// Lightweight world-space rotation rings. Dragging owns only its pointer and
// never reaches the walking/look controller. Rotation remains snapped to 90°.
export class BuildGizmo{
 constructor(camera,canvas,onRotate){this.camera=camera;this.canvas=canvas;this.onRotate=onRotate;this.root=new THREE.Group();this.root.visible=false;this.root.renderOrder=10000;this.rings=[];this.pickers=[];this.ray=new THREE.Raycaster();this.mouse=new THREE.Vector2();this.center=new THREE.Vector3();this.screen=new THREE.Vector3();this.size=new THREE.Vector3();this.drag=null;this.axis='y';this.foundation=false;
  for(const [axis,color,rotation] of [['x',0xe5a18f,[0,Math.PI/2,0]],['y',0x98d9ba,[Math.PI/2,0,0]],['z',0x98bdea,[0,0,0]]]){const ring=new THREE.Mesh(new THREE.TorusGeometry(1,.014,5,80),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.78,depthTest:false,depthWrite:false,toneMapped:false}));ring.rotation.set(...rotation);ring.userData.axis=axis;ring.renderOrder=10000;ring.frustumCulled=false;this.root.add(ring);this.rings.push(ring);const pick=new THREE.Mesh(new THREE.TorusGeometry(1,.10,5,64),new THREE.MeshBasicMaterial({visible:false,side:THREE.DoubleSide}));pick.rotation.copy(ring.rotation);pick.userData.axis=axis;this.root.add(pick);this.pickers.push(pick);}
  for(const [type,handler] of [['pointerdown',e=>this.begin(e)],['pointermove',e=>this.move(e)],['pointerup',e=>this.end(e)],['pointercancel',e=>this.end(e,true)],['lostpointercapture',e=>this.end(e,true)]])canvas.addEventListener(type,handler,{capture:true});
 }
 attach(scene){if(this.root.parent!==scene){this.cancel();scene.add(this.root);}}
 update(preview,visible,axis='y',foundation=false){this.root.visible=!!preview&&visible;this.axis=axis;this.foundation=foundation;if(!this.root.visible){this.cancel();return;}preview.updateMatrixWorld(true);preview.geometry.boundingBox.getCenter(this.center).applyMatrix4(preview.matrixWorld);preview.geometry.boundingBox.getSize(this.size);if(foundation)this.center.y=preview.position.y+.04;
  const distance=this.camera.position.distanceTo(this.center),pixel=2*distance*Math.tan(this.camera.fov*Math.PI/360)/Math.max(1,this.canvas.clientHeight||innerHeight);const radius=Math.min(Math.max(this.size.length()*.55,pixel*46),pixel*125);this.root.position.copy(this.center);this.root.scale.setScalar(Math.max(.05,radius));this.root.updateMatrixWorld(true);this.screen.copy(this.center).project(this.camera);
  this.pickers.forEach(r=>r.visible=!foundation||r.userData.axis==='y');this.rings.forEach(r=>{r.visible=!foundation||r.userData.axis==='y';r.material.opacity=r.userData.axis===axis?.95:.50;});
 }
 consume(e){e.preventDefault();e.stopImmediatePropagation();}
 begin(e){if(!this.root.visible||e.button!==0||this.drag)return;const b=this.canvas.getBoundingClientRect();this.mouse.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);this.ray.setFromCamera(this.mouse,this.camera);const hit=this.ray.intersectObjects(this.pickers.filter(r=>r.visible),false)[0];if(!hit)return;this.consume(e);const center={x:b.left+(this.screen.x*.5+.5)*b.width,y:b.top+(-this.screen.y*.5+.5)*b.height};this.drag={id:e.pointerId,axis:hit.object.userData.axis,angle:Math.atan2(e.clientY-center.y,e.clientX-center.x),center,sum:0,steps:0,x:e.clientX,y:e.clientY,moved:0};this.canvas.setPointerCapture(e.pointerId);}
 move(e){const d=this.drag;if(d?.id!==e.pointerId)return;this.consume(e);d.moved+=Math.hypot(e.clientX-d.x,e.clientY-d.y);d.x=e.clientX;d.y=e.clientY;const angle=Math.atan2(e.clientY-d.center.y,e.clientX-d.center.x);d.sum+=Math.atan2(Math.sin(angle-d.angle),Math.cos(angle-d.angle));d.angle=angle;const steps=Math.trunc(d.sum/(Math.PI/3));if(steps!==d.steps){this.onRotate(d.axis,steps-d.steps);d.steps=steps;}}
 end(e,cancel=false){const d=this.drag;if(d?.id!==e.pointerId)return;this.consume(e);this.drag=null;if(!cancel&&d.moved<7)this.onRotate(d.axis,1);if(this.canvas.hasPointerCapture?.(e.pointerId))this.canvas.releasePointerCapture(e.pointerId);}
 cancel(){if(!this.drag)return;const id=this.drag.id;this.drag=null;if(this.canvas.hasPointerCapture?.(id))this.canvas.releasePointerCapture(id);}
}
