import * as THREE from './three.module.js';
import {ITEMS,validStack} from './items.js?v=3.1';
import {createProp,propMaterial,updatePropMaterial} from './props.js?v=3.1';
import {WorldLighting,LAMP_TEMPERATURES} from './world-lighting.js?v=3.0';
const V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z),clone=x=>JSON.parse(JSON.stringify(x));
export class BuildWorld{
 constructor(scene,terrain,lunar=false){
  this.scene=scene;this.terrain=terrain;this.lunar=lunar;this.gravity=lunar?1.62:9.80665;this.entities=[];this.revision=0;this.drops=[];this.meshes=[];this.history=[];this.future=[];this.dirty=false;this.lightingDirty=true;this.lights=new WorldLighting();this.material=propMaterial(lunar);this.ghostMaterial=propMaterial(lunar,true);this.lights.attach(this.material.uniforms);
  this.ray=new THREE.Raycaster();this.ray.far=16;this._v=V();this._n=V();this._q=new THREE.Quaternion();this._p=V();this._bounds=new THREE.Box3();this._near=[];
  this.maskOrigin=new THREE.Vector2(1e6,1e6);this.maskData=new Uint8Array(512*512);this.mask=new THREE.DataTexture(this.maskData,512,512,THREE.RedFormat);this.mask.minFilter=this.mask.magFilter=THREE.NearestFilter;this.mask.generateMipmaps=false;this.maskDirty=true;
  this.storageKey='sky-expedition-world-'+(lunar?'moon':'earth')+'-v1';this.restore();
 }
 ground(x,z){return this.terrain.heightAt?.(x,z)||0;}
 snapshot(){return this.entities.map(e=>({uid:e.uid,id:e.id,position:e.position.toArray(),rotation:e.rotation.toArray().slice(0,3),params:clone(e.params)}));}
 save(){try{localStorage.setItem(this.storageKey,JSON.stringify({version:1,objects:this.snapshot(),drops:this.drops.map(d=>({stack:d.stack,position:d.mesh.position.toArray(),velocity:d.velocity.toArray(),age:d.age}))}));this.dirty=false;return true;}catch{return false;}}
 restore(){try{const data=JSON.parse(localStorage.getItem(this.storageKey));if(data)this.load(data);}catch{}}
 load(data){if(!data||!Array.isArray(data.objects))throw Error('Base no válida');for(const e of [...this.entities])this.remove(e.uid,false);for(const d of this.drops){this.scene.remove(d.mesh);if(d.mesh.geometry.userData.owned)d.mesh.geometry.dispose();}this.drops=[];
  for(const o of data.objects){if(!ITEMS[o.id]||ITEMS[o.id].tool||ITEMS[o.id].sample||!Array.isArray(o.position)||o.position.length!==3||!o.position.every(Number.isFinite)||Math.hypot(o.position[0],o.position[2])>605)continue;const r=Array.isArray(o.rotation)&&o.rotation.length===3&&o.rotation.every(Number.isFinite)?o.rotation.map(a=>Math.round(a/(Math.PI/2))*Math.PI/2):[0,0,0];this.add(o.id,V(...o.position),new THREE.Euler(...r),o.params||{},o.uid,false);}
  for(const d of data.drops||[])if(ITEMS[d.stack?.id]&&Number.isInteger(d.stack.qty)&&d.stack.qty>0&&d.stack.qty<=30&&Array.isArray(d.position)&&d.position.length===3&&d.position.every(Number.isFinite)&&Math.hypot(d.position[0],d.position[2])<610)this.spawnDrop(d.stack,V(...d.position),Array.isArray(d.velocity)&&d.velocity.length===3&&d.velocity.every(Number.isFinite)?V(...d.velocity):V(),d.age||2);
  this.history=[];this.future=[];this.dirty=false;
 }
 checkpoint(inventory){this.history.push({objects:this.snapshot()});if(this.history.length>50)this.history.shift();this.future=[];}
 undo(inventory,redo=false){const source=redo?this.future:this.history,dest=redo?this.history:this.future;if(!source.length)return false;const previous=source[source.length-1],current=this.snapshot(),oldIds=new Set(previous.objects.map(o=>o.uid)),newIds=new Set(current.map(o=>o.uid)),delta=new Map();for(const o of current)if(!oldIds.has(o.uid))delta.set(o.id,(delta.get(o.id)||0)+1);for(const o of previous.objects)if(!newIds.has(o.uid))delta.set(o.id,(delta.get(o.id)||0)-1);
  // Build a temporary inventory transaction before mutating the scene.
  const slots=inventory.snapshot();for(const [id,amount] of delta)if(amount<0){let left=-amount;for(const slot of slots)if(slot?.id===id){const n=Math.min(left,slot.qty);slot.qty-=n;left-=n;}if(left)return false;}for(let i=0;i<slots.length;i++)if(slots[i]?.qty===0)slots[i]=null;
  for(const [id,amount] of delta)if(amount>0){let left=amount;for(const slot of slots)if(slot?.id===id){const n=Math.min(30-slot.qty,left);slot.qty+=n;left-=n;}for(let i=0;i<slots.length&&left;i++)if(!slots[i]){const n=Math.min(30,left);slots[i]={id,qty:n};left-=n;}if(left)return false;}
  source.pop();const next={objects:current},h=this.history,f=this.future;const currentById=new Map(current.map(o=>[o.uid,o]));this.load({objects:previous.objects.map(o=>currentById.get(o.uid)||o),drops:this.drops.map(d=>({stack:d.stack,position:d.mesh.position.toArray(),velocity:d.velocity.toArray(),age:d.age}))});this.history=h;this.future=f;dest.push(next);inventory.restore(slots);this.dirty=true;this.save();return true;}

 add(id,position,rotation=new THREE.Euler(),params={},uid=null,save=true){const item=ITEMS[id];if(!item)return null;params={...params};params.temperature=Math.max(0,Math.min(2,Math.round(Number(params.temperature)||0)));if(params.storage)params.storage=Array.from({length:10},(_,i)=>validStack(params.storage[i]));if(params.name!==undefined)params.name=String(params.name).slice(0,32);if(params.pitch!==undefined)params.pitch=Math.max(.03,Math.min(1.5,Number(params.pitch)||.38));if(item.kind==='foundation'){params.width=Math.max(2,Math.min(24,Math.round((Number(params.width)||6)/2)*2));params.depth=Math.max(2,Math.min(24,Math.round((Number(params.depth)||6)/2)*2));if(!Number.isFinite(params.fill))params.fill=1;params.fill=Math.max(.3,Math.min(260,params.fill));}
  const mesh=createProp(id,this.material,params);mesh.position.copy(position);mesh.rotation.copy(rotation);mesh.updateMatrixWorld(true);const e={uid:uid||'o-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),id,item,position:mesh.position,rotation:mesh.rotation,params,mesh,anchor:V(),boxes:[]};mesh.userData.entity=e;this.scene.add(mesh);this.entities.push(e);this.meshes.push(mesh);this.revision++;
  this.refresh(e);if(item.category==='Iluminación'){mesh.onBeforeRender=()=>{this.material.uniforms.lampOn.value=e.params.on===false?0:1;this.material.uniforms.lampColor.value.set(LAMP_TEMPERATURES[e.params.temperature||0]?.color||0xffc38c);this.material.uniformsNeedUpdate=true;};mesh.onAfterRender=()=>{this.material.uniforms.lampOn.value=1;this.material.uniformsNeedUpdate=true;};}
  this.maskDirty=this.lightingDirty=true;if(save){this.dirty=true;this.save();}return e;
 }
 refresh(e){e.mesh.updateMatrixWorld(true);e.boxes=(e.mesh.geometry.userData.boxes||[]).map(b=>b.clone().applyMatrix4(e.mesh.matrixWorld));e.bounds=e.mesh.geometry.boundingBox.clone().applyMatrix4(e.mesh.matrixWorld);e.anchor.set(0,Math.min(e.item.size[1]+.2,1.6),0).applyMatrix4(e.mesh.matrixWorld);if(e.item.category==='Iluminación')e.anchor.set(0,e.item.kind==='ceiling-lamp'?-.18:e.item.size[1]*.92,e.item.kind==='wall-lamp'?.19:0).applyMatrix4(e.mesh.matrixWorld);}
 remove(uid,save=true){const i=this.entities.findIndex(e=>e.uid===uid);if(i<0)return;const e=this.entities[i];this.revision++;this.scene.remove(e.mesh);this.entities.splice(i,1);this.meshes.splice(this.meshes.indexOf(e.mesh),1);if(e.mesh.geometry.userData.owned)e.mesh.geometry.dispose();this.maskDirty=this.lightingDirty=true;if(save){this.dirty=true;this.save();}}
 change(e,params){Object.assign(e.params,params);this.revision++;this.lightingDirty=true;this.dirty=true;this.save();}
 support(x,z,foot=Infinity){let height=this.ground(x,z);for(const e of this.entities){if(e.bounds.max.x<x||e.bounds.min.x>x||e.bounds.max.z<z||e.bounds.min.z>z)continue;for(const b of e.boxes)if(x>=b.min.x&&x<=b.max.x&&z>=b.min.z&&z<=b.max.z&&b.max.y<=foot+.30&&b.max.y>height)height=b.max.y;}return height;}
 collide(pos,previous,radius=.22,height=1.68){const floor=pos.y-height;for(const e of this.entities){if(Math.abs(e.position.x-pos.x)>Math.max(e.item.size[0],e.params.width||0)+2||Math.abs(e.position.z-pos.z)>Math.max(e.item.size[2],e.params.depth||0)+2)continue;for(const b of e.boxes){if(b.max.y<=floor+.26||b.min.y>=pos.y-.06)continue;const minX=b.min.x-radius,maxX=b.max.x+radius,minZ=b.min.z-radius,maxZ=b.max.z+radius;if(pos.x<=minX||pos.x>=maxX||pos.z<=minZ||pos.z>=maxZ)continue;
    if(previous.x<=minX)pos.x=minX;else if(previous.x>=maxX)pos.x=maxX;else if(previous.z<=minZ)pos.z=minZ;else if(previous.z>=maxZ)pos.z=maxZ;else{const ds=[pos.x-minX,maxX-pos.x,pos.z-minZ,maxZ-pos.z],i=ds.indexOf(Math.min(...ds));if(i<2)pos.x=i?maxX:minX;else pos.z=i===2?minZ:maxZ;}
   }}return pos;}
 ceiling(x,z,foot){let ceiling=Infinity;for(const e of this.entities)for(const b of e.boxes)if(x>b.min.x-.15&&x<b.max.x+.15&&z>b.min.z-.15&&z<b.max.z+.15&&b.min.y>foot+.3)ceiling=Math.min(ceiling,b.min.y);return ceiling;}
 raycast(origin,direction,max=16){this.ray.set(origin,direction);this.ray.far=max;const hits=this.ray.intersectObjects(this.meshes,false);let hit=hits.find(h=>h.object.visible);let ground=null,previous=0;for(let t=.05;t<=max;t+=Math.max(.18,t*.018)){this._v.copy(direction).multiplyScalar(t).add(origin);if(this._v.y<=this.ground(this._v.x,this._v.z)){let lo=previous,hi=t;for(let i=0;i<9;i++){const mid=(lo+hi)/2;this._v.copy(direction).multiplyScalar(mid).add(origin);if(this._v.y>this.ground(this._v.x,this._v.z))lo=mid;else hi=mid;}const point=origin.clone().addScaledVector(direction,hi);ground={distance:hi,point,normal:V(0,1,0),entity:null};break;}previous=t;}
  if(hit&&(!ground||hit.distance<ground.distance)){const normal=hit.face.normal.clone().transformDirection(hit.object.matrixWorld);return {distance:hit.distance,point:hit.point,normal,entity:hit.object.userData.entity};}return ground;
 }
 foundationAt(x,z){return this.entities.find(e=>e.id==='foundation'&&x>=e.bounds.min.x-.05&&x<=e.bounds.max.x+.05&&z>=e.bounds.min.z-.05&&z<=e.bounds.max.z+.05);}
 foundationParams(pos,rotation,width,depth){let high=-Infinity,low=Infinity;const c=Math.cos(rotation.y),s=Math.sin(rotation.y);for(let z=-depth/2;z<=depth/2+.01;z+=.5)for(let x=-width/2;x<=width/2+.01;x+=.5){const h=this.ground(pos.x+c*x+s*z,pos.z-s*x+c*z);high=Math.max(high,h);low=Math.min(low,h);}pos.y=high+.22;return {width,depth,fill:high-low+.47};}
 snapFoundation(position,rotation,width,depth,hit){const c=Math.abs(Math.cos(rotation.y)),s=Math.abs(Math.sin(rotation.y)),hx=(width*c+depth*s)/2,hz=(width*s+depth*c)/2;let best=null,bestScore=Infinity;
  for(const e of this.entities){if(e.id!=='foundation')continue;const b=e.bounds;if(position.x<b.min.x-hx-1||position.x>b.max.x+hx+1||position.z<b.min.z-hz-1||position.z>b.max.z+hz+1)continue;const inside=hit.entity===e;const alongX=Math.round(position.x*2)/2,alongZ=Math.round(position.z*2)/2;const z=Math.max(b.min.z+Math.min(hz,(b.max.z-b.min.z)/2),Math.min(b.max.z-Math.min(hz,(b.max.z-b.min.z)/2),alongZ)),x=Math.max(b.min.x+Math.min(hx,(b.max.x-b.min.x)/2),Math.min(b.max.x-Math.min(hx,(b.max.x-b.min.x)/2),alongX));
   for(const [cx,cz,edgeDistance] of [[b.min.x-hx,z,Math.abs(position.x-b.min.x)],[b.max.x+hx,z,Math.abs(position.x-b.max.x)],[x,b.min.z-hz,Math.abs(position.z-b.min.z)],[x,b.max.z+hz,Math.abs(position.z-b.max.z)]]){const distance=Math.hypot(cx-position.x,cz-position.z),score=inside?edgeDistance:distance;if(!inside&&distance>1.25)continue;if(score>=bestScore)continue;const overlap=this.entities.some(other=>other!==e&&other.id==='foundation'&&Math.min(cx+hx,other.bounds.max.x)-Math.max(cx-hx,other.bounds.min.x)>.06&&Math.min(cz+hz,other.bounds.max.z)-Math.max(cz-hz,other.bounds.min.z)>.06);if(overlap)continue;bestScore=score;best={x:cx,z:cz,y:e.position.y,entity:e};}
  }return best;
 }
 propose(item,camera,rotation,dimensions){camera.getWorldDirection(this._n);const hit=this.raycast(camera.position,this._n,18);if(!hit)return {valid:false,reason:'Mira una superficie cercana.'};const position=hit.point.clone(),rot=rotation.clone();let params={},valid=true,reason='';
  if(item.kind==='foundation'){position.x=Math.round(position.x*2)/2;position.z=Math.round(position.z*2)/2;rot.x=rot.z=0;const snap=this.snapFoundation(position,rot,dimensions.width,dimensions.depth,hit);if(snap){position.x=snap.x;position.z=snap.z;}params=this.foundationParams(position,rot,dimensions.width,dimensions.depth);if(snap){const automaticTop=position.y,lowest=automaticTop+.25-params.fill;if(automaticTop-.22>snap.y-.02){valid=false;reason='El terreno sobrepasa este nivel; amplía hacia otra zona.';}position.y=snap.y;params.fill=Math.max(.3,snap.y-lowest+.25);params.snapped=true;}}
  else if(item.surface==='wall'){if(!hit.entity||Math.abs(hit.normal.y)>.35){valid=false;reason='Acerca la mira a una pared.';}rot.set(0,Math.atan2(hit.normal.x,hit.normal.z),0);position.addScaledVector(hit.normal,.09);position.y-=item.size[1]/2;}
  else if(item.surface==='ceiling'){if(!hit.entity||hit.normal.y>-.5){valid=false;reason='Mira la parte inferior de una cubierta.';}position.y-=.02;}
  else {
   const modular=item.category==='Construcción';if(modular){position.x=Math.round(position.x*2)/2;position.z=Math.round(position.z*2)/2;}
   if(hit.normal.y<.5&&hit.entity){if(item.kind==='roof'){position.y=hit.entity.bounds.max.y;position.x=hit.entity.position.x;position.z=hit.entity.position.z+Math.sign(hit.point.z-camera.position.z||1)*item.size[2]/2;}else position.y=hit.entity.position.y;}
   const c=Math.abs(Math.cos(rot.y)),s=Math.abs(Math.sin(rot.y)),hx=(item.size[0]*c+item.size[2]*s)/2,hz=(item.size[0]*s+item.size[2]*c)/2;
   // Join nearest modular edges first, then align centres. Mirrors Map-desing's
   // magnet thresholds without importing its editor or arbitrary scale tools.
   if(modular){let dx=.31,dz=.31;for(const e of this.entities){if(e.item.category!=='Construcción'||Math.abs(e.position.y-position.y)>3)continue;if(Math.abs(e.position.z-position.z)<hz+(e.bounds.max.z-e.bounds.min.z)/2+.4)for(const target of [e.bounds.min.x-hx,e.bounds.max.x+hx,e.bounds.min.x+hx,e.bounds.max.x-hx,e.position.x])if(Math.abs(target-position.x)<Math.abs(dx))dx=target-position.x;if(Math.abs(e.position.x-position.x)<hx+(e.bounds.max.x-e.bounds.min.x)/2+.4)for(const target of [e.bounds.min.z-hz,e.bounds.max.z+hz,e.bounds.min.z+hz,e.bounds.max.z-hz,e.position.z])if(Math.abs(target-position.z)<Math.abs(dz))dz=target-position.z;}if(Math.abs(dx)<.31)position.x+=dx;if(Math.abs(dz)<.31)position.z+=dz;}
   if(this.lunar&&item.structural){const checks=item.kind==='column'?[[0,0]]:[[-hx+.04,-hz+.04],[hx-.04,hz-.04],[hx-.04,-hz+.04],[-hx+.04,hz-.04]];if(checks.some(([x,z])=>!this.foundationAt(position.x+x,position.z+z))){valid=false;reason='Primero coloca un cimiento que cubra esta pieza.';}}
   if(item.kind!=='roof'&&hit.normal.y>.5){position.y=hit.point.y;const support=this.support(position.x,position.z,hit.point.y);if(Math.abs(support-position.y)<=.3)position.y=support;}
  }
  if(Math.hypot(position.x,position.z)>592){valid=false;reason='Construye dentro del área de exploración.';}
  if(this.entities.some(e=>e.id===item.id&&e.position.distanceTo(position)<.08&&Math.abs(Math.sin((e.rotation.y-rot.y)/2))<.01)){valid=false;reason='Ya hay una pieza en este sitio.';}
  const geo=createProp(item.id,this.ghostMaterial,params);geo.position.copy(position);geo.rotation.copy(rot);geo.updateMatrixWorld(true);const bounds=geo.geometry.boundingBox.clone().applyMatrix4(geo.matrixWorld);
  // Real supporting pieces may touch, but do not allow two solids to overlap.
  const boxes=(geo.geometry.userData.boxes||[]).map(b=>b.clone().applyMatrix4(geo.matrixWorld));
  for(const e of this.entities){if(!bounds.intersectsBox(e.bounds))continue;for(const a of boxes)for(const b of e.boxes){this._bounds.copy(a).intersect(b);const size=this._bounds.getSize(this._v);if(size.x>.06&&size.y>.06&&size.z>.06){valid=false;reason='Hay otra pieza ocupando ese espacio.';}}}
  if(geo.geometry.userData.owned)geo.geometry.dispose();
  const body=new THREE.Box3(camera.position.clone().add(V(-.24,-1.6,-.24)),camera.position.clone().add(V(.24,.1,.24)));if(boxes.some(b=>b.intersectsBox(body))){valid=false;reason='Aléjate un poco para colocar la pieza.';}
  return {valid,reason,position,rotation:rot,params,hit,overlap:reason==='Hay otra pieza ocupando ese espacio.'||reason==='Ya hay una pieza en este sitio.'};
 }
 spawnDrop(stack,position,velocity,age=0){const mesh=createProp(stack.id,this.material);mesh.scale.setScalar(.23/Math.max(...ITEMS[stack.id].size));mesh.position.copy(position);mesh.updateMatrixWorld(true);this.scene.add(mesh);const d={stack:{...stack},mesh,velocity:velocity.clone(),age,grounded:false};this.drops.push(d);this.dirty=true;return d;}
 throwStack(stack,camera){camera.getWorldDirection(this._v);this._v.y=Math.max(-.15,this._v.y);this._v.normalize();const velocity=this._v.clone().multiplyScalar(8);velocity.y=Math.max(2.8,velocity.y+2.8);const p=camera.position.clone().addScaledVector(this._v,.45);this.spawnDrop(stack,p,velocity);return true;}
 updateDrops(dt){for(const d of this.drops){d.age+=dt;if(d.grounded)continue;const steps=Math.ceil(dt*120),step=dt/steps;for(let i=0;i<steps;i++){const before=d.mesh.position.clone();d.velocity.y-=this.gravity*step;d.mesh.position.addScaledVector(d.velocity,step);this.collide(d.mesh.position,before,.12,.22);if(Math.abs(d.mesh.position.x-before.x)<.00001)d.velocity.x*=-.2;if(Math.abs(d.mesh.position.z-before.z)<.00001)d.velocity.z*=-.2;const floor=this.support(d.mesh.position.x,d.mesh.position.z,before.y)+.06;if(d.mesh.position.y<=floor){d.mesh.position.y=floor;d.grounded=true;d.velocity.set(0,0,0);this.dirty=true;break;}}if(!d.grounded)d.mesh.rotation.y+=dt*2;d.mesh.updateMatrixWorld();}}
 pickup(drop,inventory){const left=inventory.add(drop.stack.id,drop.stack.qty);if(left===drop.stack.qty)return false;if(left)drop.stack.qty=left;else{this.scene.remove(drop.mesh);if(drop.mesh.geometry.userData.owned)drop.mesh.geometry.dispose();this.drops.splice(this.drops.indexOf(drop),1);}this.dirty=true;this.save();return true;}
 updateMask(camera){if(this.lunar)return;const x=Math.floor(camera.position.x/16)*16-32,z=Math.floor(camera.position.z/16)*16-32;if(!this.maskDirty&&this.maskOrigin.x===x&&this.maskOrigin.y===z)return;this.maskOrigin.set(x,z);this.maskData.fill(0);
  for(const e of this.entities){if(!['floor','foundation'].includes(e.item.kind))continue;const b=e.bounds,minX=Math.max(0,Math.floor((b.min.x-x)*8)),maxX=Math.min(511,Math.floor((b.max.x-x)*8)),minZ=Math.max(0,Math.floor((b.min.z-z)*8)),maxZ=Math.min(511,Math.floor((b.max.z-z)*8));for(let zz=minZ;zz<=maxZ;zz++)for(let xx=minX;xx<=maxX;xx++)this.maskData[zz*512+xx]=255;}this.mask.needsUpdate=true;this.maskDirty=false;
 }
 update(camera,sky,state,t,dt){updatePropMaterial(this.material,sky,camera,state);updatePropMaterial(this.ghostMaterial,sky,camera,state);this.lights.update(this,camera.position,t);this.updateDrops(dt);this.updateMask(camera);if(this.dirty&&t-(this.lastSave||0)>1){this.lastSave=t;this.save();}}
 distanceTo(e,point){this._v.copy(point);this._v.y=Math.max(e.bounds.min.y,Math.min(e.bounds.max.y,point.y-1.3));e.bounds.clampPoint(this._v,this._p);return this._v.distanceTo(this._p);}
 powered(e){return this.entities.some(p=>['solar','power'].includes(p.item.kind)&&p.position.distanceToSquared(e.position)<18*18);}
}
