import * as THREE from './three.module.js';
import {ITEMS,itemIcon} from './items.js?v=3.1';
import {BuildWorld} from './build-world.js?v=3.1';
import {createProp,propGeometry} from './props.js?v=3.1';
import {Celestial} from './celestial.js?v=3.1';
import {BuildGizmo} from './build-gizmo.js?v=3.1';
import {LaserPointer,AstroVisor} from './field-effects.js?v=3.1';
import {FieldGuide} from './field-guide.js?v=3.1';
import {Science,escapeHTML} from './science.js?v=3.1';
const $=id=>document.getElementById(id),V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z);
const ICONS={book:'M12 5C8 2 3 3 3 3v17s5-1 9 1c4-2 9-1 9-1V3s-5-1-9 2Zm0 0v16',act:'M12 4v16M4 12h16',rotate:'M4 8a8 8 0 1 1-1 7M4 3v5h5',remove:'m4 5 16 14M20 5 4 19',undo:'M7 3 3 7l4 4M3 7h11a6 6 0 1 1 0 12',redo:'m17 3 4 4-4 4m4-4H10a6 6 0 1 0 0 12',exit:'M10 4H4v16h6m3-12 5 4-5 4m-5-4h13',seat:'M7 3v9a3 3 0 0 0 3 3h8M7 8h8v7M5 16v5m13-6v6M6 21h14',close:'m6 6 12 12M18 6 6 18',filter:'M3 5h18l-7 8v6l-4 2v-8L3 5Z'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${ICONS[name]||ICONS.act}"/></svg>`;
const INTERACTIONS={chair:'Sentarse',stool:'Sentarse',telescope:'Mirar',lab:'Analizar',desk:'Cuaderno',lamp:'Iluminar','wall-lamp':'Iluminar','ceiling-lamp':'Iluminar',radio:'Escuchar',seismometer:'Registrar',beacon:'Nombrar',weather:'Consultar',storage:'Abrir',solar:'Energía',power:'Energía'};
export class Expedition{
 constructor({state,camera,walker,renderer,inventory,getEnv,toast,setScope,setZoom,setInventory}){
  Object.assign(this,{state,camera,walker,renderer,inventory,getEnv,toast,setScope,setZoom,setInventory});this.rotation=new THREE.Euler();this.dimensions={width:6,depth:6};this.axis='y';this.preview=null;this.proposal=null;this.buildMode=false;this.visorOn=true;this.handId=null;this.lastPose=-1;this.near=null;this.seated=null;this.target=null;this.held=false;this.heldTime=0;this.scanned=false;this.lastTick=-1;this._dir=V();this._v=V();this._p=V();this.previous=V();this.previousVehicle=V();this.science=new Science(this);this.buildUI();this.guide=new FieldGuide(this);this.gizmo=new BuildGizmo(camera,renderer.domElement,(axis,steps)=>{this.axis=axis;this.rotate(steps);});this.laser=new LaserPointer();this.visor=new AstroVisor($('hud'));
  inventory.notify=toast;inventory.onDrop=stack=>this.env.world.throwStack(stack,camera);inventory.onSelect=()=>this.selectHand();inventory.onContents=()=>{if(this.handId!==inventory.hand?.id)this.selectHand();this.lastTick=this.lastPose=-1;};this.selectHand();
  this.bind();window.addEventListener('pagehide',()=>{this.env?.world.save();this.inventory.save();this.science.save();});
 }
 get env(){return this.getEnv();}
 attach(env){if(env.world)return;const lunar=env.sky.constructor.name==='LunarSky';env.world=new BuildWorld(env.scene,env.terrain,lunar);env.celestial=new Celestial(env.scene,env.sky);const world=env.world;world.lights.attach(env.terrain.u);world.lights.attach(env.vehicle.model.material.uniforms);for(const h of env.terrain.hills||[])world.lights.attach(h.material.uniforms);
  if(!lunar){env.terrain.u.buildMask={value:world.mask};env.terrain.u.buildMaskOrigin={value:world.maskOrigin};}
  env.vehicle.heightAt=(x,z)=>world.support(x,z,env.vehicle.position.y-env.vehicle.model.radius+.03);
 }
 activate(){this.attach(this.env);this.gizmo.attach(this.env.scene);this.laser.attach(this.env.scene);this.visor.last=-1;const date=localStorage.getItem('sky-expedition-date');if(date&&date!==this.env.celestial.date)this.env.celestial.setDate(date);this.walker.groundHeight=(x,z)=>this.env.world.support(x,z,this.walker.pos.y-1.68);this.walker.resolveMovement=(nx,nz)=>this.env.world.collide(this._p.set(nx,this.walker.pos.y,nz),this.walker.pos);this.lastTick=-1;this.near=null;this.clearPreview();}
 buildUI(){const hud=$('hud');const append=(tag,id,cls,html)=>{const n=document.createElement(tag);n.id=id;n.className=cls;n.innerHTML=html;hud.append(n);return n;};
  this.book=append('button','catalog-button','icon-button glass',icon('book'));this.book.type='button';this.book.setAttribute('aria-label','Abrir catálogo creativo');this.book.title='Catálogo creativo';this.book.onclick=()=>{this.setInventory(true);this.inventory.toggleCatalog(true);};
  this.aim=append('div','exp-reticle','', '<span></span>');this.aim.hidden=true;
  this.action=append('button','exp-action','icon-button glass',icon('act'));this.action.hidden=true;this.action.type='button';this.action.setAttribute('aria-label','Usar objeto seleccionado');
  this.info=append('div','exp-readout','glass','');this.info.hidden=true;
  this.tools=append('div','build-controls','build-controls glass',`<div class="build-axes" role="group" aria-label="Eje de rotación"><button type="button" data-build-axis="x" aria-label="Eje X">X</button><button type="button" data-build-axis="y" aria-label="Eje Y">Y</button><button type="button" data-build-axis="z" aria-label="Eje Z">Z</button></div><button id="build-rotate" title="Girar 90° · R" aria-label="Girar noventa grados">${icon('rotate')}</button><button id="build-remove" title="Recuperar pieza · Supr" aria-label="Recuperar pieza">${icon('remove')}</button><button id="build-undo" title="Deshacer · Ctrl Z" aria-label="Deshacer">${icon('undo')}</button><button id="build-redo" title="Rehacer · Ctrl Y" aria-label="Rehacer">${icon('redo')}</button><button id="build-cancel" title="Terminar construcción · Esc" aria-label="Terminar construcción">✓</button><div id="foundation-size" hidden><label>Ancho <input id="foundation-width" type="range" min="2" max="24" step="2" value="6"><output>6 m</output></label><label>Fondo <input id="foundation-depth" type="range" min="2" max="24" step="2" value="6"><output>6 m</output></label></div>`);this.tools.hidden=true;
  this.prompt=append('button','object-interact','vehicle-enter glass',`<span>${icon('seat')}</span><span class="enter-caption"></span>`);this.prompt.hidden=true;this.prompt.type='button';this.prompt.onclick=()=>this.interact();
  this.exitButton=append('button','object-exit','icon-button glass',icon('exit'));this.exitButton.type='button';this.exitButton.hidden=true;this.exitButton.setAttribute('aria-label','Levantarse · E');this.exitButton.onclick=()=>this.exitSeat();
  this.filtersButton=append('button','scope-filters','icon-button glass',icon('filter'));this.filtersButton.type='button';this.filtersButton.hidden=true;this.filtersButton.setAttribute('aria-label','Bandas del telescopio');this.filtersButton.onclick=()=>this.science.filters();
  this.filterLabel=append('div','scope-filter-label','','Visible');this.filterLabel.hidden=true;
  this.beacons=append('div','beacon-bearing','','');
  this.modal=append('div','science-overlay','','<section class="science-panel glass" role="dialog" aria-modal="true" aria-labelledby="science-title"><header><div><p class="eyebrow">BITÁCORA DE CAMPO</p><h2 id="science-title"></h2></div><button id="science-close" class="icon-button" aria-label="Cerrar">'+icon('close')+'</button></header><div id="science-content"></div></section>');this.modal.hidden=true;$('science-close').onclick=()=>this.closeDialog();this.modal.onclick=e=>{if(e.target===this.modal)this.closeDialog();};
  this.help=document.createElement('button');this.help.type='button';this.help.id='field-help';this.help.className='icon-button glass';this.help.textContent='?';this.help.setAttribute('aria-label','Guía de instrumentos · H');this.help.onclick=()=>this.guide.show(this.inventory.hand?.id);document.querySelector('.top-actions').prepend(this.help);
  this.lampQuick=append('button','lamp-quick','icon-button glass','<svg viewBox="0 0 24 24"><path d="M12 2v9M7 5a8 8 0 1 0 10 0"/></svg>');this.lampQuick.type='button';this.lampQuick.hidden=true;this.lampQuick.onclick=()=>{if(!this.aimedLamp)return;this.env.world.change(this.aimedLamp,{on:this.aimedLamp.params.on===false});this.tickSound();this.lastTick=-1;};
  $('inventory-main').setAttribute('aria-label','Inventario principal, 30 espacios');$('inventory-quick').setAttribute('aria-label','Diez accesos rápidos');
 }
 bind(){this.walker.bindActionButton(this.action,held=>this.actionHeld(held),true);
  this.tools.querySelectorAll('[data-build-axis]').forEach(b=>b.onclick=()=>{this.axis=b.dataset.buildAxis;this.rotate(1);});$('build-cancel').onclick=()=>this.cancelBuild();$('build-rotate').onclick=()=>this.rotate();$('build-remove').onclick=()=>this.removeAimed();$('build-undo').onclick=()=>this.undo(false);$('build-redo').onclick=()=>this.undo(true);
  for(const key of ['width','depth'])$('foundation-'+key).oninput=e=>{this.dimensions[key]=Number(e.target.value);e.target.nextElementSibling.textContent=e.target.value+' m';this.lastTick=-1;};
  let click=null;const canvas=this.renderer.domElement;
  canvas.addEventListener('pointerdown',e=>{if(this.walker.enabled&&e.button===0&&!click){click={id:e.pointerId,x:e.clientX,y:e.clientY,moved:0,heldTool:this.inventory.hand?.id==='identifier'};if(click.heldTool)this.actionHeld(true);}});
  canvas.addEventListener('pointermove',e=>{if(click?.id===e.pointerId)click.moved=Math.max(click.moved,Math.hypot(e.clientX-click.x,e.clientY-click.y));});
  canvas.addEventListener('pointerup',e=>{if(click?.id!==e.pointerId)return;const short=click.moved<7&&Math.hypot(e.clientX-click.x,e.clientY-click.y)<7,heldTool=click.heldTool;click=null;if(heldTool){this.actionHeld(false);return;}if(short&&this.buildMode)this.cancelBuild();else if(short){this.actionHeld(true);this.actionHeld(false);}});
  canvas.addEventListener('pointercancel',()=>{click=null;this.actionHeld(false);});

  window.addEventListener('keydown',e=>{if(this.state.expeditionPanel){if(e.code==='Escape'){e.preventDefault();this.closeDialog();}if(e.code==='Tab'){const nodes=[...this.modal.querySelectorAll('button,input,select,a')].filter(n=>!n.disabled&&n.offsetParent!==null),i=nodes.indexOf(document.activeElement);if((e.shiftKey&&i<=0)||(!e.shiftKey&&i===nodes.length-1)){e.preventDefault();nodes[e.shiftKey?nodes.length-1:0]?.focus();}}return;}
   if(!this.state.active||this.state.inventory||this.state.panel||e.repeat||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;
   if((e.ctrlKey||e.metaKey)&&['KeyZ','KeyY'].includes(e.code)){e.preventDefault();this.undo(e.code==='KeyY'||e.shiftKey);return;}
   if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.code==='KeyH'){e.preventDefault();this.guide.show(this.inventory.hand?.id);return;}if(e.code==='Escape'&&this.buildMode){e.preventDefault();this.cancelBuild();return;}if(e.code==='Enter'&&this.buildMode&&e.target.tagName!=='BUTTON'){e.preventDefault();this.place();return;}if(e.code==='KeyR'){e.preventDefault();this.rotate();}if(e.code==='Delete'){e.preventDefault();this.removeAimed();}if(e.code==='KeyJ'){e.preventDefault();this.science.journal();}if(e.code==='KeyC'){e.preventDefault();this.setInventory(true);this.inventory.toggleCatalog(true);}
  });window.addEventListener('blur',()=>{this.actionHeld(false);this.inventory.cancel();});
 }
 dialog(title,html){this.science.close();if(this.state.inventory)this.setInventory(false);this.state.expeditionPanel=true;document.body.classList.add('science-open');this.modal.hidden=false;$('science-title').textContent=title;$('science-content').innerHTML=html;for(const child of $('hud').children)child.inert=child!==this.modal;this.walker.enabled=false;this.walker.resetInput();this.held=false;if(document.pointerLockElement)document.exitPointerLock();$('science-close').focus();return $('science-content');}
 closeDialog(){this.science.close();this.modal.hidden=true;this.state.expeditionPanel=false;document.body.classList.remove('science-open');for(const child of $('hud').children)child.inert=false;this.walker.enabled=this.state.active&&!this.state.inventory&&!this.state.panel;this.walker.resetInput();$('world').focus({preventScroll:true});}
 tickSound(){const a=this.env.audio,c=a.ctx;if(!c)return;const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.setValueAtTime(520,c.currentTime);o.frequency.exponentialRampToValueAtTime(310,c.currentTime+.05);g.gain.setValueAtTime(.07,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.08);o.connect(g);g.connect(a.master);o.start();o.stop(c.currentTime+.09);o.onended=()=>{o.disconnect();g.disconnect();};}
 clearPreview(){if(this.preview){this.preview.removeFromParent();if(this.preview.geometry.userData.owned)this.preview.geometry.dispose();}this.preview=null;this.previewId=null;this.proposal=null;this.previewPose=null;}
 selectHand(){this.handId=this.inventory.hand?.id;const item=ITEMS[this.handId];this.buildMode=!!item&&!item.tool&&!item.sample;this.visorOn=true;this.lastTick=this.lastPose=-1;this.justPlaced=null;this.held=false;this.heldTime=0;this.scanned=false;if(!this.buildMode)this.clearPreview();}
 cancelBuild(){this.buildMode=false;this.justPlaced=null;this.clearPreview();this.gizmo.root.visible=false;this.gizmo.cancel();this.tools.hidden=true;this.action.hidden=true;this.aim.hidden=true;this.info.hidden=true;this.lastTick=this.lastPose=-1;}
 rotate(steps=1){const item=ITEMS[this.inventory.hand?.id];if(!this.buildMode||!item||item.tool||item.sample||this.seated)return;if(item.kind==='foundation'&&this.axis!=='y')this.axis='y';const quarter=Math.round(this.rotation[this.axis]/(Math.PI/2))+steps;this.rotation[this.axis]=((quarter%4)+4)%4*Math.PI/2;this.lastTick=this.lastPose=-1;this.tickSound();}
 actionHeld(held){this.held=held;if(!held){this.heldTime=0;this.scanned=false;this.scanTap=false;return;}if(!this.walker.enabled)return;const hand=this.inventory.hand,item=ITEMS[hand?.id];if(this.state.mountedScope){this.science.observe(this.target);return;}if(!item)return;
  if(item.tool){switch(item.id){case 'visor':this.visorOn=!this.visorOn;this.lastTick=-1;break;case 'identifier':this.scanned=false;this.heldTime=0;break;case 'spectrometer':this.science.spectrum(this.target);break;case 'notebook':this.science.journal();break;case 'camera':this.science.photo(this.target);break;case 'sampler':{this.camera.getWorldDirection(this._dir);const hit=this.env.world.raycast(this.camera.position,this._dir,3);if(!hit||hit.entity)return this.toast('Apunta al suelo natural, a menos de tres metros.');const id=this.state.destination==='moon'?'regolith':'soil';if(this.inventory.add(id,1))this.toast('Necesitas una casilla libre.');else{this.tickSound();this.toast(ITEMS[id].name+' ×1 recogida.');}break;}case 'rangefinder':{const hit=this.measure();this.toast(hit?'Distancia: '+hit.distance.toFixed(2)+' m':'Apunta a una superficie dentro de 600 m.');break;}}return;}
  if(item.sample)return this.toast('Lleva esta muestra a una mesa de análisis.');if(this.buildMode)this.place();
 }
 place(){const item=ITEMS[this.inventory.hand?.id];if(!this.buildMode||!item||item.tool||item.sample||this.seated||this.env.vehicle.mounted)return;const p=this.env.world.propose(item,this.camera,this.rotation,this.dimensions);if(!p.valid)return this.toast(p.reason);this.env.world.checkpoint(this.inventory);this.env.world.add(item.id,p.position,p.rotation,p.params);this.justPlaced={id:item.id,position:p.position.clone()};this.clearPreview();this.inventory.consume(30+this.inventory.selected);this.tickSound();this.lastTick=this.lastPose=-1;}
 removeAimed(){if(this.seated||this.env.vehicle.mounted)return;this.camera.getWorldDirection(this._dir);const hit=this.env.world.raycast(this.camera.position,this._dir,8),e=hit?.entity;if(!e)return this.toast('Mira una pieza a menos de ocho metros.');if(e.item.kind==='foundation'&&this.env.world.entities.some(a=>a!==e&&a.position.x>=e.bounds.min.x&&a.position.x<=e.bounds.max.x&&a.position.z>=e.bounds.min.z&&a.position.z<=e.bounds.max.z&&a.position.y>=e.position.y-.05))return this.toast('Recupera primero las piezas apoyadas en este cimiento.');if(e.params.storage?.some(Boolean))return this.toast('Vacía primero la caja.');const inv=this.inventory;if(!inv.slots.some(s=>!s||(s.id===e.id&&s.qty<30)))return this.toast('Tu mochila está llena.');this.env.world.checkpoint(inv);inv.add(e.id,1);this.env.world.remove(e.uid);this.lastTick=-1;this.tickSound();}
 undo(redo){if(this.seated||this.env.vehicle.mounted)return;if(this.env.world.undo(this.inventory,redo)){this.lastTick=-1;this.tickSound();}else this.toast(redo?'No hay cambios para rehacer.':'No hay cambios para deshacer.');}
 beforeMotion(){this.previous.copy(this.walker.pos);this.previousVehicle.copy(this.env.vehicle.position);}
 afterMotion(){const w=this.walker,world=this.env.world;if(!w.driver){const ceiling=world.ceiling(w.pos.x,w.pos.z,this.previous.y-1.68);if(w.pos.y>ceiling-.05&&this.previous.y<=ceiling+.08){w.pos.y=ceiling-.05;w.verticalSpeed=Math.min(0,w.verticalSpeed);w.camera.position.y=w.pos.y;}}
  else if(w.driver===this.env.vehicle){const vehicle=this.env.vehicle,before=vehicle.position.clone();this._p.copy(vehicle.position).add(V(0,1.2,0));world.collide(this._p,this.previousVehicle.clone().add(V(0,1.2,0)),.80,1.56);vehicle.position.x=this._p.x;vehicle.position.z=this._p.z;if(Math.hypot(vehicle.position.x-before.x,vehicle.position.z-before.z)>.001){vehicle.speed*=.2;vehicle.applyPose(0);w.camera.position.x+=vehicle.position.x-before.x;w.camera.position.z+=vehicle.position.z-before.z;}}
 }
 measure(){this.camera.getWorldDirection(this._dir);const hit=this.env.world.raycast(this.camera.position,this._dir,600);this.env.world.ray.far=600;const vh=this.env.world.ray.intersectObject(this.env.vehicle.root,true)[0];return vh&&(!hit||vh.distance<hit.distance)?vh:hit;}
 update(t,dt,ratio){const {world,sky,celestial}=this.env;if(!world)return;celestial.update(this.state,ratio);world.update(this.camera,sky,this.state,t,dt);this.science.tick?.(t);const playing=this.state.active&&!this.state.inventory&&!this.state.panel&&!this.state.expeditionPanel&&!this.state.hiddenUI;
  if(t-this.lastTick>.08||this.lastTick<0){this.lastTick=t;this.updateInteraction(playing);const identify=playing&&(this.state.mountedScope||['identifier','spectrometer','camera','visor'].includes(this.inventory.hand?.id));if(identify){const candidate=celestial.identify(this.camera,this.state);this.camera.getWorldDirection(this._dir);this.target=candidate&&!world.raycast(this.camera.position,candidate.direction||this._dir,1000)?candidate:null;}else this.target=null;this.updateAimedLamp(playing);this.updateReadout(playing);this.updateBeacons();}
  if(t-this.lastPose>1/30||this.lastPose<0){this.lastPose=t;this.updateHand(playing);this.updateReadout(playing);}
  if(this.held&&this.inventory.hand?.id==='identifier'&&!this.scanned&&playing){if(this.target&&this.target.id===this.scanId)this.heldTime+=dt;else{this.scanId=this.target?.id;this.heldTime=0;}this.action.style.setProperty('--scan',Math.min(100,this.heldTime/.65*100)+'%');if(this.heldTime>=.65){this.scanned=true;this.science.observe(this.target);}}
  if(!this.held)this.action.style.setProperty('--scan','0%');
  const show=playing&&this.buildMode&&!this.env.vehicle.mounted&&!this.seated&&!!this.proposal?.position&&!this.proposal?.overlap&&!(this.justPlaced?.id===this.previewId&&this.justPlaced.position.distanceTo(this.proposal.position)<.2);
  if(this.preview)this.preview.visible=show;this.gizmo.update(this.preview,show,this.axis,this.previewId==='foundation');
  const laserActive=playing&&this.inventory.hand?.id==='rangefinder'&&!this.seated;this.laserHit=laserActive?this.measure():null;this.laser.update(this.camera,this.laserHit,laserActive);this.visor.update(this.camera,celestial,this.state,world,t,playing&&this.inventory.hand?.id==='visor'&&this.visorOn);
 }
 updateAimedLamp(playing){this.aimedLamp=null;if(playing&&!this.state.scope){this.camera.getWorldDirection(this._dir);const hit=this.env.world.raycast(this.camera.position,this._dir,12);if(hit?.entity?.item.category==='Iluminación')this.aimedLamp=hit.entity;}this.lampQuick.hidden=!this.aimedLamp;if(this.aimedLamp){const on=this.aimedLamp.params.on!==false;this.lampQuick.setAttribute('aria-pressed',on);this.lampQuick.setAttribute('aria-label',(on?'Apagar':'Encender')+' lámpara');this.lampQuick.title=(on?'Apagar':'Encender')+' lámpara';}}
 updateHand(playing){const item=ITEMS[this.inventory.hand?.id],build=this.buildMode&&item&&!item.tool&&!item.sample&&!this.seated&&!this.env.vehicle.mounted;const available=playing&&!this.state.scope&&!this.env.vehicle.mounted&&!this.seated;this.tools.hidden=!available||!build;this.action.hidden=!playing||(!((item?.tool||build)&&!this.env.vehicle.mounted&&!this.seated)&&!this.state.mountedScope);this.aim.hidden=this.action.hidden&&!this.aimedLamp;this.info.hidden=this.action.hidden;
  if(this.state.mountedScope){this.action.setAttribute('aria-label','Registrar observación');this.action.innerHTML=icon('act');}
  else if(item){this.action.setAttribute('aria-label',build?'Colocar '+item.name:'Usar '+item.name);const mode=build?'place':item.id;if(this.action.dataset.mode!==mode){this.action.dataset.mode=mode;this.action.innerHTML=build?icon('act'):itemIcon(item);}}
  $('foundation-size').hidden=!build||item?.kind!=='foundation';this.tools.querySelectorAll('[data-build-axis]').forEach(b=>{b.setAttribute('aria-pressed',b.dataset.buildAxis===this.axis);b.disabled=item?.kind==='foundation'&&b.dataset.buildAxis!=='y';});
  if(!build||!available){this.clearPreview();return;}
  const p=this.camera.position,q=this.camera.quaternion,r=this.rotation;
  const pose=[this.env.world,this.env.world.revision,item.id,p.x,p.y,p.z,q.x,q.y,q.z,q.w,r.x,r.y,r.z,this.dimensions.width,this.dimensions.depth];
  if(this.preview&&this.previewPose&&pose.every((value,i)=>value===this.previewPose[i]))return;
  const proposal=this.env.world.propose(item,this.camera,this.rotation,this.dimensions);this.proposal=proposal;
  const key=item.id+(item.id==='foundation'?JSON.stringify(proposal.params):'');if(this.preview?.userData.key!==key){this.clearPreview();this.preview=createProp(item.id,this.env.world.ghostMaterial,proposal.params);this.preview.userData.key=key;this.previewId=item.id;this.env.scene.add(this.preview);this.proposal=proposal;}
  if(proposal.position){this.preview.position.copy(proposal.position);this.preview.rotation.copy(proposal.rotation);this.preview.updateMatrixWorld();}this.preview.visible=!!proposal.position&&!proposal.overlap;this.env.world.ghostMaterial.uniforms.valid.value=proposal.valid?1:0;this.previewPose=pose;
 }
 updateReadout(playing){if(this.info.hidden||!playing)return;const item=ITEMS[this.inventory.hand?.id];let text='';if(this.state.mountedScope)text=this.target?this.target.name+' · acción para registrar':'Telescopio de piso · mueve la mirada para orientarlo';else if(item?.tool){text=item.name;if(item.id==='identifier')text=this.target?this.target.name+' · mantén para identificar':'Apunta a un astro y mantén acción';if(item.id==='rangefinder'){const h=this.laserHit;text=h?h.distance.toFixed(2)+' m':'Sin impacto · el rayo se disipa';}if(item.id==='visor')text=this.visorOn?'Visor celeste · acción para quitar':'Visor apagado · acción para poner';if(item.id==='spectrometer'&&this.target?.kind==='star')text=this.target.name+' · '+this.target.type+' · ≈ '+this.target.temperature+' K';}else if(item)text=item.name+' ×'+this.inventory.hand.qty+(this.proposal?.valid?(this.proposal.params.snapped?' · Unido al cimiento · +':' · + Colocar'):this.proposal?.reason?' · '+this.proposal.reason:'');this.info.textContent=text;}
 updateInteraction(playing){this.near=null;if(!playing||this.seated||this.env.vehicle.mounted||this.state.scope)return;let closest=Infinity;for(const e of this.env.world.entities){const action=INTERACTIONS[e.item.kind];if(!action)continue;const range=['chair','stool'].includes(e.item.kind)?.5:1.4,d=this.env.world.distanceTo(e,this.camera.position);if(d>range||d>=closest)continue;this._v.copy(e.anchor).project(this.camera);if(this._v.z< -1||this._v.z>1||Math.abs(this._v.x)>.97||Math.abs(this._v.y)>.95)continue;const direction=e.anchor.clone().sub(this.camera.position),distance=direction.length();const hit=this.env.world.raycast(this.camera.position,direction.normalize(),distance);if(hit?.entity&&hit.entity!==e)continue;this.near={entity:e,action,anchor:e.anchor};closest=d;}
  for(const d of this.env.world.drops){if(d.age<.9)continue;const distance=d.mesh.position.distanceTo(this.camera.position);if(distance<2.3&&distance<closest+1){this._v.copy(d.mesh.position).project(this.camera);if(Math.abs(this._v.x)<.85&&Math.abs(this._v.y)<.9&&this._v.z<1){this.near={drop:d,action:'Recoger',anchor:d.mesh.position};closest=distance;}}}
 }
 updatePrompt(){const visible=!!this.near&&this.state.active&&!this.state.inventory&&!this.state.panel&&!this.state.expeditionPanel&&!this.state.hiddenUI&&!this.seated;this.prompt.hidden=!visible;if(visible){this._v.copy(this.near.anchor).project(this.camera);if(this._v.z>1||this._v.z< -1){this.prompt.hidden=true;return false;}this.prompt.style.transform=`translate3d(${(this._v.x*.5+.5)*innerWidth}px,${(-this._v.y*.5+.5)*innerHeight}px,0) translate(-50%,-50%)`;const text=this.near.action+' · E';this.prompt.querySelector('.enter-caption').textContent=text;this.prompt.setAttribute('aria-label',text);}return visible;}
 interact(){if(this.state.expeditionPanel)return true;if(this.seated){this.exitSeat();return true;}if(!this.near)return false;const {entity:e,drop}=this.near;if(drop){if(!this.env.world.pickup(drop,this.inventory))this.toast('Tu mochila está llena.');this.near=null;return true;}const k=e.item.kind;
  if(k==='chair'||k==='stool'||k==='telescope')this.sit(e);else if(e.item.category==='Iluminación')this.science.lamp(e);else if(k==='lab')this.science.analyze(e);else if(k==='desk')this.science.journal();else if(k==='radio')this.science.radio(e);else if(k==='seismometer')this.science.seismometer();else if(k==='weather')this.science.weather();else if(k==='beacon')this.science.beacon(e);else if(k==='storage')this.science.storage(e);else if(k==='solar'||k==='power')this.dialog('Energía del puesto','<p>Este módulo habilita aparatos avanzados a menos de 18 metros. Funciona sin cables ni consumo de combustible.</p>');return true;
 }
 sit(entity){this.cancelBuild();const telescope=entity.item.kind==='telescope';this.setScope(false);this.walker.resetInput();this.seated={entity,telescope,oldPitch:this.walker.pitch,oldYaw:this.walker.yaw};this.clearPreview();this.walker.yaw=-entity.rotation.y;this.walker.pitch=telescope?(entity.params.pitch??.38):.04;const seat=telescope?V(0,1.42-Math.sin(this.walker.pitch)*.75,-.2+Math.cos(this.walker.pitch)*.75).applyMatrix4(entity.mesh.matrixWorld):V(0,1.22,0).applyMatrix4(entity.mesh.matrixWorld);this.walker.driver={jump(){},resetInput(){},drive(dt,w){if(telescope){w.pitch=Math.max(.03,Math.min(1.5,w.pitch));entity.rotation.y=-w.yaw;entity.params.pitch=w.pitch;entity.mesh.updateMatrixWorld();seat.set(0,1.42-Math.sin(w.pitch)*.75,-.2+Math.cos(w.pitch)*.75).applyMatrix4(entity.mesh.matrixWorld);}w.pos.copy(seat);w.camera.position.copy(seat);w.camera.rotation.set(w.pitch,-w.yaw,0,'YXZ');w.grounded=true;}};
  this.exitButton.hidden=false;document.body.classList.add('seated');this.filtersButton.hidden=!telescope;this.filterLabel.hidden=!telescope;this.state.mountedScope=telescope;if(telescope){entity.mesh.visible=false;this.setScope(true);this.setZoom(1);this.renderer.domElement.dataset.filter=this.science.filter;}this.near=null;this.prompt.hidden=true;
 }
 exitSeat(){if(!this.seated)return false;const {entity,telescope}=this.seated;this.state.mountedScope=false;if(this.state.expeditionPanel)this.closeDialog();if(telescope){entity.mesh.visible=true;if(entity.mesh.geometry.userData.owned)entity.mesh.geometry.dispose();entity.mesh.geometry=propGeometry('telescope',entity.params);this.env.world.refresh(entity);this.env.world.save();this.renderer.domElement.dataset.filter='visible';this.setScope(false);this.setZoom(0);}this.state.mountedScope=false;this.walker.driver=null;const p=entity.position;let exit=null;for(let i=0;i<8;i++){const a=entity.rotation.y+i*Math.PI/4,x=p.x+Math.cos(a)*1,z=p.z+Math.sin(a)*1,y=this.env.world.support(x,z,p.y)+1.68;this._v.set(x,y,z);this._p.copy(this._v);this.env.world.collide(this._v,this._p,.22,1.68);if(this._v.distanceTo(this._p)<.01){exit=this._v.clone();break;}}this.walker.pos.copy(exit||p.clone().add(V(1,this.env.world.ground(p.x+1,p.z)-p.y+1.68,0)));this.walker.verticalSpeed=0;this.walker.grounded=true;this.walker.resetInput();this.seated=null;this.exitButton.hidden=true;this.filtersButton.hidden=true;this.filterLabel.hidden=true;document.body.classList.remove('seated');$('world').focus({preventScroll:true});return true;}
 updateBeacons(){if(!this.state.active){this.beacons.textContent='';return;}const candidates=this.env.world.entities.filter(e=>e.item.kind==='beacon');const rows=candidates.map(e=>{const d=e.position.clone().sub(this.camera.position),bearing=Math.atan2(d.x,-d.z),delta=Math.atan2(Math.sin(bearing-this.walker.yaw),Math.cos(bearing-this.walker.yaw));return {e,delta,dist:Math.hypot(d.x,d.z)};}).filter(a=>Math.abs(a.delta)<Math.PI/3).sort((a,b)=>a.dist-b.dist).slice(0,2);this.beacons.textContent=rows.map(a=>(a.delta<-.15?'‹ ':a.delta>.15?'› ':'◇ ')+(a.e.params.name||'Baliza')+' · '+Math.round(a.dist)+' m').join('   ');}
 export(){this.env.world.save();const read=key=>{try{return JSON.parse(localStorage.getItem(key));}catch{return null;}};const data={format:'sky-expedition',version:1,inventory:{slots:this.inventory.snapshot(),selected:this.inventory.selected},worlds:{earth:read('sky-expedition-world-earth-v1'),moon:read('sky-expedition-world-moon-v1')},journal:this.science.entries,date:this.env.celestial.date};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Sky-Explorer-expedicion.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);this.toast('Expedición exportada.');}
 async import(file){if(!file)return;try{if(file.size>12000000)throw Error('Archivo demasiado grande.');const d=JSON.parse(await file.text());if(d.format!=='sky-expedition'||d.version!==1||!Array.isArray(d.inventory?.slots)||!d.worlds)throw Error('No es una expedición compatible.');for(const name of ['earth','moon'])if(d.worlds[name]&&(!Array.isArray(d.worlds[name].objects)||d.worlds[name].objects.length>10000))throw Error('La base contiene datos no válidos.');
   this.importPending=d;const c=this.dialog('Importar expedición','<p>La expedición importada reemplazará tus bases, mochila y cuaderno de este navegador. Puedes exportar antes la expedición actual.</p><button id="backup-before-import">Exportar la actual</button><button id="confirm-field-import" class="science-primary">Reemplazar por el archivo elegido</button>');c.querySelector('#backup-before-import').onclick=()=>this.export();c.querySelector('#confirm-field-import').onclick=()=>{for(const name of ['earth','moon'])localStorage.setItem('sky-expedition-world-'+name+'-v1',JSON.stringify(d.worlds[name]||{version:1,objects:[],drops:[]}));this.inventory.restore(d.inventory.slots);this.inventory.select(Number(d.inventory.selected)||0);this.science.entries=Array.isArray(d.journal)?d.journal.filter(e=>e&&typeof e==='object'&&typeof e.title==='string').slice(-160):[];this.science.unlocked=this.science.unlocks();this.science.save();if(d.date)this.env.celestial.setDate(d.date);this.env.world.load(d.worlds[this.state.destination]||{objects:[]});window.dispatchEvent(new Event('expedition-import'));this.closeDialog();this.toast('Expedición importada.');};
  }catch(e){this.toast(e.message||'No se pudo importar el archivo.');}}
}
